servers:
  server_name_1: 3.2.1.1
  server_name_2: 124.124.124.124
  server_name_3: cyberomanov.tech
  server_name_4: cyberomanov.me

settings:

  # telegram
  bot_api_key: "2078979512:AAGVo9omO-IP8cr_VuBqChKgqkoRpulRgIk"
  alarm_chat_id: "-748451309"

  # privacy. if 'true', then "178.x.x.19". if 'false', then "178.18.17.19"
  streamer_mode: true

  # output
  online_emoji: "\U0001F7E2"
  offline_emoji: "\U0001F534"
  message_template: "{emoji} {name} /// {host} {emoji} | {text}."
