servers:
  server_name_1: 3.2.1.1
  server_name_2: 124.124.124.124
  server_name_3: cyberomanov.tech
  server_name_4: cyberomanov.me

settings:

  # telegram
  bot_api_key: "1703:AA-BB_CC"
  alarm_chat_id: "-2109"
  
  # output
  online_emoji: "\U0001F7E2"
  offline_emoji: "\U0001F534"
  message_template: "{emoji} {name} /// {host} {emoji}"
  
  # logic
  streamer_mode: true            # if true: "178.x.x19", else: "178.18.17.19"
  sleep_time_between_loops: 60   # in seconds
  log_output: "./log/ping.log"
  log_rotation: "500 MB"
  
